# Generated by Django 5.1.3 on 2026-08-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField()),
                ('error', models.TextField()),
                ('stream_entry_id', models.CharField(blank=True, default='', max_length=40)),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(db_index=True)),
                ('tick_rate_per_min', models.FloatField(default=0)),
                ('committer_lag_seconds', models.FloatField(default=0)),
                ('stream_depth', models.IntegerField(default=0)),
                ('dlq_depth', models.IntegerField(default=0)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('settings_silence_threshold', models.IntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('CONNECT', 'Connect'), ('DISCONNECT', 'Disconnect'), ('RESUBSCRIBE', 'Resubscribe'), ('ERROR', 'Error'), ('DLQ', 'DLQ'), ('LAG', 'Lag')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('account_id', models.IntegerField()),
                ('exch_seg', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=40)),
                ('symbol', models.CharField(blank=True, default='', max_length=40)),
                ('ltp', models.DecimalField(decimal_places=4, max_digits=18)),
                ('volume', models.BigIntegerField(default=0)),
                ('open', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('high', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('low', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('close', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('avg_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
            ],
            options={
                'indexes': [models.Index(fields=['account_id', 'token', 'time'], name='ticks_tick_account_f3d0be_idx'), models.Index(fields=['exch_seg', 'token', 'time'], name='ticks_tick_exch_se_cf898a_idx')],
            },
        ),
    ]
