# Generated by Django 5.1.3 on 2026-08-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=40)),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('symbol_finvasia', models.CharField(default='', max_length=40)),
                ('name', models.CharField(default='', max_length=80)),
                ('exch_seg', models.CharField(db_index=True, max_length=10)),
                ('expiry', models.CharField(blank=True, max_length=40, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('strike', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('option_type', models.CharField(blank=True, default='', max_length=2)),
                ('lot_size', models.IntegerField(default=1)),
                ('tick_size', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('instrument_type', models.CharField(blank=True, default='', max_length=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['exch_seg', 'symbol'], name='instruments_exch_se_d03c6a_idx'), models.Index(fields=['exch_seg', 'token'], name='instruments_exch_se_782fea_idx')],
                'unique_together': {('exch_seg', 'token')},
            },
        ),
    ]
