# Generated by Django 5.1.3 on 2026-08-20 13:08

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(choices=[('FINVASIA', 'Finvasia (Shoonya)')], default='FINVASIA', max_length=20)),
                ('nickname', models.CharField(max_length=80)),
                ('client_id', models.CharField(max_length=40)),
                ('password', django_cryptography.fields.encrypt(models.CharField(max_length=128))),
                ('totp_secret', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=128))),
                ('api_key', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=128))),
                ('vendor_code', models.CharField(blank=True, default='', max_length=40)),
                ('access_token', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256))),
                ('source_ip', models.GenericIPAddressField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_login_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nickname'],
                'unique_together': {('owner', 'client_id', 'broker')},
            },
        ),
    ]
