# Generated by Django 5.1.3 on 2026-08-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First chars of the key, for identification in lists.', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('scoped_accounts', models.ManyToManyField(blank=True, related_name='api_keys', to='accounts.brokeraccount')),
                ('scoped_scripts', models.ManyToManyField(blank=True, related_name='api_keys', to='instruments.script')),
            ],
        ),
    ]
