# Generated by Django 5.1.3 on 2026-08-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size', models.IntegerField(default=500)),
                ('flush_interval_seconds', models.FloatField(default=2.0)),
                ('retention_days', models.IntegerField(default=365)),
                ('compress_after_days', models.IntegerField(default=7)),
                ('alert_lag_seconds', models.IntegerField(default=60, help_text='SystemEvent warning when committer lag exceeds this.')),
                ('account', models.OneToOneField(blank=True, help_text='Leave blank for the global default config.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streaming_config', to='accounts.brokeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='StreamingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_state', models.CharField(choices=[('STOPPED', 'Stopped'), ('RUNNING', 'Running'), ('PAUSED', 'Paused')], default='STOPPED', max_length=10)),
                ('actual_state', models.CharField(choices=[('STOPPED', 'Stopped'), ('RUNNING', 'Running'), ('PAUSED', 'Paused')], default='STOPPED', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_stopped_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_setting', to='accounts.brokeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.brokeraccount')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='instruments.script')),
            ],
            options={
                'unique_together': {('account', 'script')},
            },
        ),
    ]
